language: c
compiler:
  - gcc
  - clang
env: CFLAGS="-coverage -O0" LDFLAGS="-coverage"
before_install:
  - pip install --user codecov
script: make && make test
after_success:
  # This workaround is required to force proper report generation.
  - gcov -p -b -o build/ src/*.c
  - gcov -p -b -o build/test/ test/*.c
  - codecov
