language: c
compiler:
  - gcc
  - clang
env: CFLAGS="-coverage -O0" LDFLAGS="-coverage"
before_install:
  - pip install --user cpp-coveralls
script: make && make test
after_success:
  - coveralls -b . -x .c -e test/ -e src/test.c -e src/test-common.c
